from django.urls import path
from .views import (
    AboutV2View,
    AboutView,
    ApiHowToV2View,
    ApiHowToView,
    ColorView,
    GlossaryView,
    GraphFormView,
    GraphV2View,
    HistoryV2View,
    HistoryView,
    RegisterView,
    SiteLoginView,
    StatsV2View,
    StatsView,
    run_latest_agile,
    run_update,
    stats_plot,
    update_status,
)

urlpatterns = [
    path("accounts/login/", SiteLoginView.as_view(), name="login"),
    path("accounts/register/", RegisterView.as_view(), name="register"),
    path("update", run_update, name="run_update"),
    path("update/latest_agile", run_latest_agile, name="run_latest_agile"),
    path("update/status", update_status, name="update_status"),
    path("stats/plot/<path:filename>", stats_plot, name="stats_plot"),
    path("color", ColorView.as_view(), name="color"),
    path("stats", StatsView.as_view(), name="api_how_to"),
    path("api_how_to", ApiHowToView.as_view(), name="api_how_to"),
    path("glossary", GlossaryView.as_view(), name="glossary"),
    path("about", AboutView.as_view(), name="about"),
    path("history", HistoryView.as_view(), name="history"),
    path("history/", HistoryView.as_view(), name="history"),
    path("history/<str:region>/", HistoryView.as_view(), name="history"),
    path("v2/", GraphV2View.as_view(), name="graph_v2"),
    path("v2/history/", HistoryV2View.as_view(), name="history_v2"),
    path("v2/history/<str:region>/", HistoryV2View.as_view(), name="history_v2_region"),
    path("v2/stats/", StatsV2View.as_view(), name="stats_v2"),
    path("v2/about/", AboutV2View.as_view(), name="about_v2"),
    path("v2/api_how_to/", ApiHowToV2View.as_view(), name="api_how_to_v2"),
    path("v2/<str:region>/", GraphV2View.as_view(), name="graph_v2_region"),
    path("<str:region>/", GraphFormView.as_view(), name="graph"),
    path("", GraphFormView.as_view(), name="graph"),
]
