# Generated by Django 4.2.11 on 2024-04-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forecasts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.DateTimeField()),
                ("date_time", models.DateTimeField()),
                ("day_ahead", models.FloatField()),
                ("agile", models.FloatField()),
                ("wind", models.FloatField()),
                ("bm_wind", models.FloatField()),
                ("solar", models.FloatField()),
                ("temp_2m", models.FloatField()),
                ("wind_10m", models.FloatField()),
                ("irradience", models.FloatField()),
                ("day_of_week", models.IntegerField()),
                ("hour_of_day", models.FloatField()),
                ("day_of_year", models.IntegerField()),
                ("demand_source", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ForecastData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.DateTimeField()),
                ("date_time", models.DateTimeField()),
                ("day_ahead", models.FloatField()),
                ("agile", models.FloatField()),
                ("wind", models.FloatField()),
                ("bm_wind", models.FloatField()),
                ("solar", models.FloatField()),
                ("temp_2m", models.FloatField()),
                ("wind_10m", models.FloatField()),
                ("irradience", models.FloatField()),
                ("day_of_week", models.IntegerField()),
                ("hour_of_day", models.FloatField()),
                ("day_of_year", models.IntegerField()),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prices.forecasts",
                    ),
                ),
            ],
        ),
    ]
