# Generated by Django 4.2.11 on 2024-04-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0003_remove_forecastdata_day_of_week_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forecastdata",
            old_name="irradience",
            new_name="rad",
        ),
        migrations.RenameField(
            model_name="history",
            old_name="irradience",
            new_name="rad",
        ),
    ]
