# Generated by Django 4.2.11 on 2024-04-24 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0005_pricehistory_remove_history_agile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricehistory",
            name="date_time",
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
