# Generated by Django 4.2.11 on 2024-04-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0011_rename_agile_forecastdata_agile_pred_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecastdata",
            name="agile_actual",
            field=models.FloatField(),
        ),
    ]
