# Generated by Django 4.2.11 on 2024-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0012_alter_forecastdata_agile_actual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecastdata",
            name="agile_actual",
            field=models.FloatField(null=True),
        ),
    ]
