# Generated by Django 4.2.11 on 2024-04-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0014_alter_forecastdata_agile_pred_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forecastdata",
            name="wind",
        ),
        migrations.RemoveField(
            model_name="history",
            name="wind",
        ),
    ]
