# Generated by Django 4.2.11 on 2024-04-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0015_remove_forecastdata_wind_remove_history_wind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forecastdata",
            name="agile_actual",
        ),
        migrations.RemoveField(
            model_name="forecastdata",
            name="agile_pred",
        ),
        migrations.CreateModel(
            name="AgileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=1)),
                ("agile_pred", models.FloatField()),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="prices.forecasts",
                    ),
                ),
            ],
        ),
    ]
