# Generated by Django 4.2.11 on 2024-04-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0016_remove_forecastdata_agile_actual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastdata",
            name="day_ahead",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
