# Generated by Django 4.2.11 on 2024-04-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0018_agiledata_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastdata",
            name="intercon_capacity",
            field=models.FloatField(default=8900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forecastdata",
            name="other_gen_capacity",
            field=models.FloatField(default=40000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="intercon_capacity",
            field=models.FloatField(default=8900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="other_gen_capacity",
            field=models.FloatField(default=40000),
            preserve_default=False,
        ),
    ]
