# Generated by Django 4.2.11 on 2024-04-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0019_forecastdata_intercon_capacity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forecastdata",
            name="intercon_capacity",
        ),
        migrations.RemoveField(
            model_name="forecastdata",
            name="other_gen_capacity",
        ),
        migrations.RemoveField(
            model_name="history",
            name="intercon_capacity",
        ),
        migrations.RemoveField(
            model_name="history",
            name="other_gen_capacity",
        ),
    ]
