# Generated by Django 4.2.11 on 2024-05-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0020_remove_forecastdata_intercon_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agiledata",
            name="agile_high",
            field=models.FloatField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agiledata",
            name="agile_low",
            field=models.FloatField(default=18),
            preserve_default=False,
        ),
    ]
