# Generated by Django 4.2.11 on 2024-05-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0021_agiledata_agile_high_agiledata_agile_low"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nordpool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(unique=True)),
                ("day_ahead", models.FloatField()),
                ("agile", models.FloatField()),
            ],
        ),
    ]
