# Generated by Django 4.2.11 on 2024-05-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0022_nordpool"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastdata",
            name="emb_wind",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
