# Generated by Django 4.2.11 on 2024-05-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0024_history_total_wind"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateErrors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("type", models.CharField(max_length=10)),
                ("dataset", models.CharField(max_length=32)),
                ("source", models.CharField(max_length=255)),
            ],
        ),
    ]
