# Generated by Django 4.2.11 on 2025-03-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0025_updateerrors"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Nordpool",
        ),
        migrations.RemoveField(
            model_name="updateerrors",
            name="source",
        ),
    ]
