# Generated by Django 4.2.11 on 2025-03-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0026_delete_nordpool_remove_updateerrors_source"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UpdateErrors",
        ),
    ]
