# Generated by Django 4.2.20 on 2025-04-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0027_delete_updateerrors"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecasts",
            name="mean",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecasts",
            name="stdev",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="forecastdata",
            name="day_ahead",
            field=models.FloatField(null=True),
        ),
    ]
