# Generated by Django 4.2.20 on 2026-05-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0032_plotimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='gas_ttf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='nuclear',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='gas_ttf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='nuclear',
            field=models.FloatField(default=0),
        ),
    ]
