# Generated by Django 4.2.20 on 2026-05-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0033_forecastdata_gas_ttf_forecastdata_nuclear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('agileforecast', 'AgileForecast'), ('x2r', 'X2R')], max_length=32)),
                ('region', models.CharField(max_length=2)),
                ('forecast_name', models.CharField(blank=True, max_length=128)),
                ('source_created_at', models.DateTimeField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('date_time', models.DateTimeField()),
                ('agile_pred', models.FloatField()),
                ('agile_low', models.FloatField(blank=True, null=True)),
                ('agile_high', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'region', 'source_created_at'], name='prices_exte_source_3c0ec2_idx'), models.Index(fields=['source', 'region', 'date_time'], name='prices_exte_source_b10df5_idx')],
                'unique_together': {('source', 'region', 'source_created_at', 'date_time')},
            },
        ),
    ]
