# Generated by Django 4.2.20 on 2026-06-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0038_create_access_groups"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequestClientSeen",
        ),
        migrations.DeleteModel(
            name="RequestMetric",
        ),
    ]
