# Generated by Django 4.2.20 on 2026-06-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0039_delete_requestclientseen_delete_requestmetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastdata",
            name="fr_nuclear",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forecastdata",
            name="opmr_surplus",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
