# Generated by Django 4.2.20 on 2026-06-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0040_forecastdata_fr_nuclear_forecastdata_opmr_surplus"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastdata",
            name="interconnector_flow",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
