# Generated by Django 4.2.20 on 2026-06-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0041_forecastdata_interconnector_flow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forecastdata",
            old_name="interconnector_flow",
            new_name="fr_price",
        ),
    ]
