# Generated by Django 4.2.20 on 2026-06-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0042_rename_interconnector_flow_to_fr_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forecastdata",
            old_name="fr_price",
            new_name="fr_wind",
        ),
        migrations.AddField(
            model_name="forecastdata",
            name="fr_rad",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
