# Generated by Django 4.2.11 on 2026-06-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0043_replace_fr_price_with_fr_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='shap_top_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
