# Generated by Django 4.2.11 on 2026-06-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0044_forecastdata_shap_top_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='melngc_margin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
