# Generated by Django 4.2.11 on 2026-06-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0045_forecastdata_melngc_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='opmr_national_surplus',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
