# Generated by Django 4.2.11 on 2026-06-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0046_forecastdata_opmr_national_surplus'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='gas_availability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
