# Generated by Django 4.2.11 on 2026-06-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0047_forecastdata_gas_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastdata',
            old_name='opmr_surplus',
            new_name='dispatchable_capacity',
        ),
    ]
