# Generated by Django 4.2.11 on 2026-07-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0048_rename_opmr_surplus_forecastdata_dispatchable_capacity'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agiledata',
            index=models.Index(fields=['region', 'date_time'], name='prices_agil_region_0f2191_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastdata',
            index=models.Index(fields=['date_time'], name='prices_fore_date_ti_6e118b_idx'),
        ),
    ]
