# Generated by Django 4.2.11 on 2026-08-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0049_agiledata_prices_agil_region_0f2191_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KofiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kofi_transaction_id', models.CharField(max_length=64, unique=True)),
                ('message_id', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('payment_type', models.CharField(blank=True, max_length=32)),
                ('from_name', models.CharField(blank=True, max_length=128)),
                ('message', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('is_public', models.BooleanField(default=True)),
                ('is_subscription_payment', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
