# Generated by Django 4.2.11 on 2026-08-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0050_kofipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='day_ahead_corrected',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DayAheadCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(unique=True)),
                ('created_at', models.DateTimeField()),
                ('horizon_h', models.FloatField()),
                ('predicted', models.FloatField()),
                ('actual', models.FloatField()),
                ('surplus', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['date_time'], name='prices_daya_date_ti_1d9129_idx')],
            },
        ),
    ]
