"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from environs import Env

env = Env()
env.read_env(override=True)

# import dj_database_url
#

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)
ENV = env("ENV", default="production")
LOCAL_REALTIME_EXTERNAL_FORECASTS = DEBUG and ENV.lower() in {"development", "local"}

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["agilepredict.com", ".agilepredict.com", ".fly.dev"])
UPDATE_TOKEN = env("UPDATE_TOKEN", default="")


LOG_DIR = os.path.join(BASE_DIR, "logs")
Path(LOG_DIR).mkdir(parents=True, exist_ok=True)  # ensure it exists

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "utils_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "utils.log"),
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "config.utils": {
            "handlers": ["utils_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "prices.api": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "prices.web": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "prices.worker": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    # 3rd Party
    "rest_framework",
    "crispy_forms",
    "crispy_bootstrap5",
    # Local
    "prices",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "prices.middleware.RequestMetricsMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "prices.context_processors.selected_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }
    "default": env.dj_db_url("DATABASE_URL", default="sqlite:///db.sqlite3"),
}
# DATABASES = {
#     "default": dj_database_url.config(  # Replace this value with your local database's connection string.
#         default="postgresql://postgres:postgres@localhost:5432/mysite",
#         conn_max_age=600,
#     )
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "plots"]
STATIC_ROOT = BASE_DIR / "static"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CSRF_TRUSTED_ORIGINS = ["https://*.fly.dev", "https://*.agilepredict.com"]


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"  # new
CRISPY_TEMPLATE_PACK = "bootstrap5"  # new

GLOBAL_SETTINGS = {
    "DATASETS": {
        "bm_wind": {
            "name": "Metered Wind",
            "source": "National Grid ESO",
        },
        "demand": {
            "name": "Demand",
            "source": "National Grid ESO",
        },
        "NATIONALDEMAND": {
            "name": "Demand (Interim History)",
            "source": "Elexon BMRS",
        },
        "solar": {
            "name": "Embedded Solar",
            "source": "National Grid ESO",
        },
        "total_wind": {
            "name": "Total Wind",
            "source": "National Grid ESO",
        },
        "temp_2m": {
            "name": "Temperature",
            "source": "Open Meteo",
        },
        "wind_10m": {
            "name": "Wind Speed",
            "source": "Open Meteo",
        },
        "rad": {
            "name": "Solar Radiation",
            "source": "Open Meteo",
        },
    },
    "UPDATE_TIME": "09:00",
    "AGILE_RELEASE_TIME": "16:00",
    "SHIFTS": {
        "2020-01-01 00:00:00": 0.0,
        "2026-04-01 00:00:00": -3.5,
    },
    "REGIONS": {
        "X": {
            "name": "National Average",
            "factors": (0.2136, 12.21),
            "export_factors": (0.0950, 0.9979, 5.8464),
        },
        "A": {
            "name": "Eastern England",
            "factors": (0.21, 13),
            "export_factors": (0.095, 1.09, 7.04),
        },
        "B": {
            "name": "East Midlands",
            "factors": (0.20, 14),
            "export_factors": (0.094, 0.78, 6.27),
        },
        "C": {
            "name": "London",
            "factors": (0.20, 12),
            "export_factors": (0.095, 1.30, 5.93),
        },
        "D": {
            "name": "Merseyside and Northern Wales",
            "factors": (0.22, 13),
            "export_factors": (0.097, 1.26, 5.97),
        },
        "E": {
            "name": "West Midlands",
            "factors": (0.21, 11),
            "export_factors": (0.094, 0.77, 6.50),
        },
        "F": {
            "name": "North Eastern England",
            "factors": (0.21, 12),
            "export_factors": (0.095, 0.87, 4.88),
        },
        "G": {
            "name": "North Western England",
            "factors": (0.21, 12),
            "export_factors": (0.096, 1.10, 5.89),
        },
        "H": {
            "name": "Southern England",
            "factors": (0.21, 12),
            "export_factors": (0.094, 0.93, 7.05),
        },
        "J": {
            "name": "South Eastern England",
            "factors": (0.22, 12),
            "export_factors": (0.094, 1.09, 7.41),
        },
        "K": {
            "name": "Southern Wales",
            "factors": (0.22, 12),
            "export_factors": (0.094, 0.97, 5.46),
        },
        "L": {
            "name": "South Western England",
            "factors": (0.23, 11),
            "export_factors": (0.093, 0.83, 7.14),
        },
        "M": {
            "name": "Yorkshire",
            "factors": (0.20, 13),
            "export_factors": (0.096, 0.72, 5.78),
        },
        "N": {
            "name": "Southern Scotland",
            "factors": (0.21, 13),
            "export_factors": (0.097, 0.90, 3.85),
        },
        "P": {
            "name": "Northern Scotland",
            "factors": (0.24, 12),
            "export_factors": (0.096, 1.36, 2.68),
        },
    },
}
